language: java

jdk: oraclejdk8

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/apache-maven-3.3.9"

before_install:
- export M2_HOME=$HOME/apache-maven-3.3.9
- if [ ! -d $M2_HOME/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz | tar zxf - -C $HOME; fi
- export PATH=$M2_HOME/bin:$PATH

sudo: false

install: true

env:
- MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=512m"

# have to skip tests for now as travis currently includes only jdk8u31
script: mvn verify -B -DskipTests=true -Darguments=-DskipTests

notifications:
  email: false
